// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0rBQQb40fM8f7HggGLi_rLL7b9qbFcVM',
    appId: '1:163486389453:web:c6b0272000040183ee0584',
    messagingSenderId: '163486389453',
    projectId: 'attendance-app-81d28',
    authDomain: 'attendance-app-81d28.firebaseapp.com',
    storageBucket: 'attendance-app-81d28.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZD3grMbVI0qL1c522lsVtY4Kl38fVhkc',
    appId: '1:163486389453:android:743377ca82deef05ee0584',
    messagingSenderId: '163486389453',
    projectId: 'attendance-app-81d28',
    storageBucket: 'attendance-app-81d28.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA4gxtMLGg9e1j5rzuWb3Ye8QUICEeWJw',
    appId: '1:163486389453:ios:a7792110ef192a95ee0584',
    messagingSenderId: '163486389453',
    projectId: 'attendance-app-81d28',
    storageBucket: 'attendance-app-81d28.firebasestorage.app',
    iosBundleId: 'com.soumil.attendenceapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCA4gxtMLGg9e1j5rzuWb3Ye8QUICEeWJw',
    appId: '1:163486389453:ios:f1f2819a5ecdfe7bee0584',
    messagingSenderId: '163486389453',
    projectId: 'attendance-app-81d28',
    storageBucket: 'attendance-app-81d28.firebasestorage.app',
    iosBundleId: 'com.example.attendence',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0rBQQb40fM8f7HggGLi_rLL7b9qbFcVM',
    appId: '1:163486389453:web:481c36badb8f1f12ee0584',
    messagingSenderId: '163486389453',
    projectId: 'attendance-app-81d28',
    authDomain: 'attendance-app-81d28.firebaseapp.com',
    storageBucket: 'attendance-app-81d28.firebasestorage.app',
  );

}